#rll_cell_1:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000

  # Trajectory Controllers ---------------------------------------
  #
  # Forward Position Controllers ---------------------------------------
  PositionJointInterface_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - iiwa_1_joint_1
      - iiwa_1_joint_2
      - iiwa_1_joint_3
      - iiwa_1_joint_4
      - iiwa_1_joint_5
      - iiwa_1_joint_6
      - iiwa_1_joint_7

    constraints:
      goal_time: 2.0                   # Override default

    state_publish_rate:  1000            # Override default
    action_monitor_rate: 30            # Override default
    stop_trajectory_duration: 0.5        # Override default

  # Forward Position Controllers ---------------------------------------
  PosVelJointInterface_trajectory_controller:
    type: pos_vel_controllers/JointTrajectoryController
    joints: 
      - iiwa_1_joint_1
      - iiwa_1_joint_2
      - iiwa_1_joint_3
      - iiwa_1_joint_4
      - iiwa_1_joint_5
      - iiwa_1_joint_6
      - iiwa_1_joint_7

    constraints:
      goal_time: 2.0                   # Override default

    state_publish_rate:  1000            # Override default
    action_monitor_rate: 30            # Override default
    stop_trajectory_duration: 0.5        # Override default

  # Gripper controller ---------------------------------------------
  PositionJointInterface_gripper_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - iiwa_1_egl_position
      - iiwa_1_egl_position_mimic
    gains:
      iiwa_1_egl_position: {p: 500,  d: 10, i: 2, i_clamp: 10}
      iiwa_1_egl_position_mimic: {p: 500,  d: 10, i: 2, i_clamp: 10}
    constraints:
      goal_time: 0.5
      iiwa_1_egl_position:
        goal: 0.02
      iiwa_1_egl_position_mimic:
        goal: 0.02
