db_name: rll_test

# URLs
api_base_url: http://localhost:8888/
logs_base_url: http://localhost/logs
cams_base_url: http://localhost
git_archive_dir: /home/rll/projects/test
logs_save_dir: /home/rll/logs/test

secret: SET_YOUR_SECRET_HERE

sub_queue_limit: 70

projects:
  - tower_of_hanoi
  - greetings
  - rll_planning_project
  - test_projects

project_settings:
  rll_planning_project:
    launch_iface: planning_iface.launch
    launch_client: path_planner.launch
  greetings:
    launch_iface: move_iface.launch
    launch_client: move_sender.launch
  tower_of_hanoi:
    launch_iface: move_iface.launch
    launch_client: move_sender.launch
  test_projects:
    launch_iface: move_iface.launch
    launch_client: move_sender.launch

