db_name: rll_test

# URLs
api_base_url: http://localhost:8888/
logs_base_url: http://localhost/logs
cams_base_url: http://localhost
git_archive_dir: /home/rll/projects/test
logs_save_dir: /home/rll/logs/test

secret: SET_YOUR_SECRET_HERE

# IP address of the host running the workers
host_ip: SET_YOUR_IP_HERE

projects:
  - tower_of_hanoi
  - greetings
  - rll_planning_project

project_settings:
  rll_planning_project:
    launch_iface: planning_iface.launch
    launch_client: path_planner.launch
    sync_services_to_client:
        - move
        - check_path
    sync_actions_to_host:
        - plan_to_goal
    action_publisher:
        plan_to_goal: path_planner
  greetings:
    launch_iface: move_iface.launch
    launch_client: move_sender.launch
  tower_of_hanoi:
    launch_iface: move_iface.launch
    launch_client: move_sender.launch
