db_name: rll_test

# URLs
api_base_url: http://localhost:8888/
logs_base_url: http://localhost/logs
cams_base_url: http://localhost
git_archive_dir: /home/rll/projects/test
logs_save_dir: /home/rll/logs/test

secret: SET_YOUR_SECRET_HERE

projects:
  - tower_of_hanoi
  - greetings
  - rll_planning_project

project_settings:
  rll_planning_project:
    launch_client: path_planner.launch
    launch_iface: planning_iface.launch
    iface_docker_image: rll-planning-project
    iface_project: rll_planning_project
    iface_node: planning_iface
    sync_services_to_client:
        - move
        - check_path
    sync_actions_to_host:
        - plan_to_goal
    action_publisher:
        plan_to_goal: path_planner
  greetings:
    launch_client: move_sender.launch
    launch_iface: move_iface.launch
    iface_docker_image: rll-base
    iface_project: rll_move_real
    iface_node: move_iface
    sync_services_to_client:
        - move_joints
    sync_actions_to_host:
        - move_client
    action_publisher:
        move_client: greetings
  tower_of_hanoi:
    launch_client: move_sender.launch
    launch_iface: move_iface.launch
    iface_docker_image: rll-base
    iface_project: rll_move_real
    iface_node: move_iface
    sync_services_to_client:
        - move_lin
        - pick_place
    sync_actions_to_host:
        - move_client
    action_publisher:
        move_client: tower_hanoi
